### ISSUE TITLE
Github organization 

### ISSUE THREAD

**Issue by fzerorubigd** [fzerorubigd/cal-events#4]
پیشنهاد برای اسم پذیرفته میشه :)‌و اگه کسی امکان همکاری داره هم من با کمال میل اضافش میکنم بهش.

**Comment by saeedek** [comment]
من تا جایی که بتونم خوشحال می شم همکاری کنم.

**Comment by dariubs** [comment]
پیشنهاد اسم:
persiancal

میتونیم توش کتابخونه‌های اساسی دیگه مثل jcal رو هم برای میتین داشته باشیم 
و با کمال میل حاضرم هر همکاری که بتونم داشته باشم :)

**Comment by fzerorubigd** [comment]
چون پیشنهاد دیگه‌ای نیست، و من هم واقعا تو انتخاب اسم بد هستم همین اسم رو استفاده میکنیم. ممنون.
